apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: volume-admission-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
