apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: volume-admission
webhooks:
  - name: volume-admission.tools.wmcloud.org
    clientConfig:
      service:
        name: volume-admission
        namespace: {{ .Release.Namespace }}
        path: "/"
      caBundle: {{ .Values.webhook.caBundle }}
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    matchPolicy: Equivalent
    sideEffects: None
    admissionReviewVersions: ["v1"]
    objectSelector:
      {{ .Values.webhook.objectSelector | toYaml | nindent 6 }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
