apiVersion: v1
kind: Namespace
metadata:
  name: tool-test
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: tool-test
  labels:
    toolforge: tool
spec:
  containers:
    - command:
        - sleep
        - "3600"
      image: debian:bullseye
      name: test
