---
apiVersion: v1
kind: Namespace
metadata:
  name: volume-admission
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volume-admission-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
  - kind: ServiceAccount
    name: default
    namespace: volume-admission
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: volume-admission
  name: volumes-config
data:
  volumes.json: |-
    [
      {
        "name": "dumps",
        "path": "/public/dumps",
        "type": "Directory",
        "readOnly": true
      },
      {
        "name": "dumpsrc1",
        "path": "/mnt/nfs/dumps-labstore1007.wikimedia.org",
        "type": "Directory",
        "readOnly": true
      },
      {
        "name": "dumpsrc2",
        "path": "/mnt/nfs/dumps-labstore1006.wikimedia.org",
        "type": "Directory",
        "readOnly": true
      },
      {
        "name": "home",
        "path": "/data/project",
        "type": "Directory",
        "readOnly": false
      },
      {
        "name": "wmcs-project",
        "path": "/etc/wmcs-project",
        "type": "File",
        "readOnly": true
      },
      {
        "name": "scratch",
        "path": "/data/scratch",
        "type": "Directory",
        "readOnly": false
      },
      {
        "name": "etcldap-conf",
        "path": "/etc/ldap.conf",
        "type": "File",
        "readOnly": true
      },
      {
        "name": "etcldap-yaml",
        "path": "/etc/ldap.yaml",
        "type": "File",
        "readOnly": true
      },
      {
        "name": "etcnovaobserver-yaml",
        "path": "/etc/novaobserver.yaml",
        "type": "File",
        "readOnly": true
      },
      {
        "name": "sssd-pipes",
        "path": "/var/lib/sss/pipes",
        "type": "Directory",
        "readOnly": false
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-admission
  namespace: volume-admission
  labels:
    name: volume-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      name: volume-admission
  template:
    metadata:
      name: volume-admission
      labels:
        name: volume-admission
    spec:
      containers:
        - name: webhook
          image: volume-admission:latest
          imagePullPolicy: Never
          env:
            - name: "DEBUG"
              value: "true"
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 50Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: volumes-config
              mountPath: /etc/volumes.json
              subPath: volumes.json
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: volume-admission-certs
        - name: volumes-config
          configMap:
            name: volumes-config
            items:
              - key: volumes.json
                path: volumes.json
---
apiVersion: v1
kind: Service
metadata:
  name: volume-admission
  namespace: volume-admission
  labels:
    name: volume-admission
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 8080
  selector:
    name: volume-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: volume-admission
webhooks:
  - name: volume-admission.tools.wmcloud.org
    clientConfig:
      service:
        name: volume-admission
        namespace: volume-admission
        path: "/"
      caBundle: --CA_BUNDLE--
    failurePolicy: Ignore
    matchPolicy: Equivalent
    sideEffects: None
    admissionReviewVersions: ["v1"]
    objectSelector:
      matchLabels:
        toolforge: tool
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
---
