apiVersion: v1
kind: Service
metadata:
  name: volume-admission
  namespace: volume-admission
  labels:
    name: volume-admission
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 8080
  selector:
    name: volume-admission
