apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: volume-admission
webhooks:
  - name: volume-admission.tools.wmcloud.org
    clientConfig:
      service:
        name: volume-admission
        namespace: volume-admission
        path: "/"
      caBundle: --CA_BUNDLE--
    failurePolicy: Ignore
    matchPolicy: Equivalent
    sideEffects: None
    admissionReviewVersions: ["v1"]
    objectSelector:
      matchLabels:
        toolforge: tool
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
