apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-admission
  namespace: volume-admission
  labels:
    name: volume-admission
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: webhook
          image: volume-admission:latest
          imagePullPolicy: Never
          env:
            - name: "DEBUG"
              value: "true"
