replicas: 2

image:
  name: docker-registry.tools.wmflabs.org/volume-admission
  tag: latest
  pullPolicy: Fail

resources:
  limits:
    memory: 50Mi
    cpu: 300m
  requests:
    memory: 50Mi
    cpu: 300m

webhook:
  secretName: volume-admission-certs
  failurePolicy: Ignore
  objectSelector:
    matchLabels:
      toolforge: tool

volumes:
  - name: dumps
    path: "/public/dumps"
    type: Directory
    readOnly: true
  - name: dumpsrc-clouddumps1001
    path: "/mnt/nfs/dumps-clouddumps1001.wikimedia.org"
    type: Directory
    readOnly: true
  - name: dumpsrc-clouddumps1002
    path: "/mnt/nfs/dumps-clouddumps1002.wikimedia.org"
    type: Directory
    readOnly: true
  - name: home
    path: "/data/project"
    type: Directory
    readOnly: false
  - name: wmcs-project
    path: "/etc/wmcs-project"
    type: File
    readOnly: true
  - name: scratch
    path: "/data/scratch"
    type: Directory
    readOnly: false
  - name: etcldap-conf
    path: "/etc/ldap.conf"
    type: File
    readOnly: true
  - name: etcldap-yaml
    path: "/etc/ldap.yaml"
    type: File
    readOnly: true
  - name: etcnovaobserver-yaml
    path: "/etc/novaobserver.yaml"
    type: File
    readOnly: true
  - name: sssd-pipes
    path: "/var/lib/sss/pipes"
    type: Directory
    readOnly: false

debug: false
